const MODIFIER_COLLAPSED = 'collapsed';
const MODIFIER_EXPANDED = 'expanded';
const MODIFIER_HIDDEN = 'hidden';
const MODIFIER_DISABLED = 'disabled';
const MODIFIER_SELECTED = 'selected';
const MODIFIER_INVALID = 'invalid';
const MODIFIER_FOCUSED = 'focused';


const MODIFIERS = {
    COLLAPSED: MODIFIER_COLLAPSED,
    HIDDEN: MODIFIER_HIDDEN,
    DISABLED: MODIFIER_DISABLED,
    SELECTED: MODIFIER_SELECTED,
    INVALID: MODIFIER_INVALID,
    FOCUSED: MODIFIER_FOCUSED,
    EXPANDED: MODIFIER_EXPANDED,
};

export default MODIFIERS;

export {
    MODIFIER_COLLAPSED,
    MODIFIER_EXPANDED,
    MODIFIER_HIDDEN,
    MODIFIER_DISABLED,
    MODIFIER_SELECTED,
    MODIFIER_INVALID,
    MODIFIER_FOCUSED,
}
